targetTopic: ${TARGET_TOPIC}

logging:
  level:
    ch.raciborski.kafka: DEBUG

spring:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}:${PORT}
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: false
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: c0desurfer
      properties:
        spring:
          json:
            trusted:
              packages: ch.raciborski.kafka
      enable-auto-commit: false
    ssl:
      trust-store-location: file://${TRUSTSTORE_LOCATION}
      trust-store-password: ${TRUSTSTORE_PASSWORD}
      trust-store-type: PKCS12
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-512
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${SCRAM_USERNAME}" password="${SCRAM_PASSWORD}";